baseURL = "https://ragnarlevi.github.io/"
title = "Ragnar"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Ragnar Leví Guðmundarson"
    badge = "orange"
    quote = "red"
#    notice = "Hello, world. This is a notification."
#    notice_color = "red"
    index_posts_num = 5
    google_search = true
    math = true
    # logo = "/self/img/red_panda.png" #Logo for the home button in the upper right corner
    bio = """
    <p> Welcome to my personal website where I post random notebooks about machine learning topics (with applications in Risk and Insurance). </p>
    <br />
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "Publications"
    name = "Publications"
    url = "/Publications/"
    weight = 10

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10


# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1


[taxonomies]
# category = "Categories"
tag = "tags"
# series = "series"

# [[menu.icon]]
#     url = "mailto:username@mail.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
#     url = "https://github.com/username/"
#     name = "github"
#     weight = 1

# [[menu.icon]]
#     url = "https://twitter.com/username"
#     name = "twitter"
#     weight = 1

# [[menu.icon]]
#    url = "https://www.instagram.com/username/"
#    name = "instagram"
#    weight = 1
